### ISSUE TITLE
Failed to install python

### ISSUE THREAD

**Issue by leakedby** [Yuk1n0/Shadowsocks-Install#2]
Failed to install python

No match for argument: python
There are following alternatives for "python": python2, python36, python38

How to fix this?

Which python version you recommend?

**Comment by Yuk1n0** [comment]
Which Linux distribution are you using now?

**Comment by leakedby** [comment]
Ubuntu 18.06

**Comment by Yuk1n0** [comment]
Hi, I have tested script on Ubuntu. Regrettably I couldn't reproduce this fault

Therefore, I suggest you manually execute the following command:
`sudo apt install python python3`

**Comment by Kaabi** [comment]
I receive the same error 
[Error] Failed to install python on CentOS Linux release 8.4.2105

I have python3 & 2 installed already

[root@storage ~]# yum install python python3
Last metadata expiration check: 0:00:55 ago on Sun 29 Aug 2021 01:21:00 AM CEST.
No match for argument: python
There are following alternatives for "python": python2, python36, python38, python39
Package python36-3.6.8-2.module_el8.4.0+790+083e3d81.x86_64 is already installed.

**Comment by karelianAzeroy** [comment]
I would like to add that I also have this issue OS: Ubuntu 24.04.2 LTS aarch64

**Comment by MrLeyYT** [comment]
```
root@its:~# sudo apt install python python3
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package python is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python-is-python3 2to3

E: Package 'python' has no installation candidate
```

**Comment by MrLeyYT** [comment]
I fixed it. 
Just change line 311 to 
```libtool make openssl perl python3 qrencode unzip```
