### ISSUE TITLE
How to change the obfs_param

### ISSUE THREAD

**Issue by vantechcorner** [Yuk1n0/Shadowsocks-Install#6]
Hi,

I see in /etc/shadowsocks-r/config.json there is the obfs_param.
How can I change it on the server side?

Thank you!

**Comment by Yuk1n0** [comment]
Sorry for my late reply.

You can refer to this document: https://github.com/shadowsocksr-rm/shadowsocks-rss/blob/master/ssr.md

If you still have problems, please leave a message under this issue, I'll keep this issue open.

**Comment by vantechcorner** [comment]
No worry. Thank you for the response!
