### ISSUE TITLE
It doesn't support UDP?

### ISSUE THREAD

**Issue by ortwinbachmann30** [Yuk1n0/Shadowsocks-Install#7]
Hello, it doesn't support UDP?
It has installed without any problem.
![Snag_901531](https://user-images.githubusercontent.com/74976078/103205032-e0367580-490d-11eb-869c-3a66634adf0d.png)

**Comment by Yuk1n0** [comment]
Hi, you can find shadowsocks-libev's configuration file in **/etc/shadowsocks-libev/config.json** and add the following line:

`"mode": "tcp_and_udp"`

**Comment by ortwinbachmann30** [comment]
Thank you so much. It worked.
![Snag_1001cd1](https://user-images.githubusercontent.com/74976078/103405698-38b77e00-4b6d-11eb-9a83-19144f182ed6.png)

**Comment by ortwinbachmann30** [comment]
Thank you so much. It worked.
![Snag_1014ca7](https://user-images.githubusercontent.com/74976078/103405740-66042c00-4b6d-11eb-84eb-1bf044a4196a.png)
